name: build_and_test

on:
  pull_request:
    branches: [ "master" ] # .... 
  # push:  
  #   branches: [ "devel" ] # temp 
  workflow_dispatch:  

jobs:
  build_on_pull_request:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}    

      - name: get some info
        run: |
          pwd 
          python -V 

      - name: Build
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Install dependencies for testing 
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install dist/*.whl

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Verify FFmpeg
        run: ffmpeg -version    

      - name: get pip list
        run: pip list   

      - name: Run tests 
        run: |
          pytest -s


